# Generated by Django 3.1.7 on 2021-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardfront',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
