# Generated by Django 3.1.7 on 2021-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcardfront_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardfront',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
